-- Disposable local E2E identities. Never apply to development or production.
insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)values
(md5('e2e-gold')::uuid,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','gold.customer@example.invalid',crypt('PilotTest!2026',gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}','{}',now(),now()),
(md5('e2e-admin')::uuid,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','staff.admin@example.invalid',crypt('PilotTest!2026',gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}','{}',now(),now()),
(md5('e2e-unlinked')::uuid,'00000000-0000-0000-0000-000000000000','authenticated','authenticated','unlinked@example.invalid',crypt('PilotTest!2026',gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}','{}',now(),now());
insert into auth.identities(id,user_id,provider_id,identity_data,provider,last_sign_in_at,created_at,updated_at)values
(gen_random_uuid(),md5('e2e-gold')::uuid,md5('e2e-gold')::uuid::text,jsonb_build_object('sub',md5('e2e-gold')::uuid,'email','gold.customer@example.invalid'),'email',now(),now(),now()),
(gen_random_uuid(),md5('e2e-admin')::uuid,md5('e2e-admin')::uuid::text,jsonb_build_object('sub',md5('e2e-admin')::uuid,'email','staff.admin@example.invalid'),'email',now(),now(),now()),
(gen_random_uuid(),md5('e2e-unlinked')::uuid,md5('e2e-unlinked')::uuid::text,jsonb_build_object('sub',md5('e2e-unlinked')::uuid,'email','unlinked@example.invalid'),'email',now(),now(),now());
insert into public.reward_accounts(id,kind,display_name,normalized_key)values(md5('e2e-gold-account')::uuid,'individual','E2E Gold Customer','e2e-gold-customer');insert into public.profiles(id,individual_account_id,display_name,role)values(md5('e2e-gold')::uuid,md5('e2e-gold-account')::uuid,'E2E Gold Customer','customer'),(md5('e2e-admin')::uuid,null,'E2E Staff Admin','admin');
insert into public.orders(id,external_order_number,account_id,site_id,site_name,order_type,status,ordered_at,paid_at,amount_billed,raw_payload)values(md5('e2e-gold-order')::uuid,'E2E-GOLD-001',md5('e2e-gold-account')::uuid,'onward-customs','Onward Customs','E2E','Paid in full','2026-06-01 12:00:00+00','2026-06-01 12:00:00+00',5200,'{"e2e":true}');select public.rebuild_tier_achievements(md5('e2e-gold-account')::uuid);insert into public.reward_ledger(account_id,reward_type,amount,description,expires_at)values(md5('e2e-gold-account')::uuid,'reward_credit_usd',50,'E2E reward credit','2027-12-31');
