/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import Link from"next/link";import{FormEvent,useEffect,useState}from"react";import RedemptionAdmin from"@/components/redemption-admin";import SupportAdmin from"@/components/support-admin";import OperationsHealth from"@/components/operations-health";import{CheckCircle2,FileSpreadsheet,MessageSquareMore,ShieldAlert,UserPlus,XCircle}from"lucide-react";import{getSupabaseBrowserClient}from"@/lib/supabase/client";
type RequestRow={id:string;status:string;submitted_at:string|null;requirements:Record<string,boolean>;completed_requirements:number;reward_accounts:{display_name:string}|null};type Account={id:string;display_name:string;kind:"individual"|"company";active:boolean;current_tier:string};
export default function AdminDashboard(){const[access,setAccess]=useState<"checking"|"allowed"|"denied">("checking"),[rows,setRows]=useState<RequestRow[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[email,setEmail]=useState(""),[name,setName]=useState(""),[accountId,setAccountId]=useState(""),[relationship,setRelationship]=useState("individual"),[sending,setSending]=useState(false),[message,setMessage]=useState("");
async function load(){const s=getSupabaseBrowserClient();if(!s)return;const[{data:r},{data:a}]=await Promise.all([s.from("verification_requests").select("id,status,submitted_at,requirements,completed_requirements,reward_accounts(display_name)").order("submitted_at",{ascending:false}),s.rpc("staff_onboarding_accounts")]);setRows((r??[])as unknown as RequestRow[]);setAccounts((a??[])as Account[])}
useEffect(()=>{const s=getSupabaseBrowserClient();if(!s){setAccess("denied");return}s.auth.getUser().then(async({data})=>{if(!data.user){setAccess("denied");return}const{data:p}=await s.from("profiles").select("role").eq("id",data.user.id).single();if(p?.role==="staff"||p?.role==="admin"){setAccess("allowed");await load()}else setAccess("denied")})},[]);
function selectAccount(id:string){setAccountId(id);const a=accounts.find(x=>x.id===id);setRelationship(a?.kind==="company"?"company_member":"individual")}
async function invite(e:FormEvent){e.preventDefault();setSending(true);setMessage("");const{data,error}=await getSupabaseBrowserClient()!.functions.invoke("onboard-customer",{body:{action:"invite",email,displayName:name,accountId,relationship}});setSending(false);let safeError=data?.error as string|undefined;if(error&&!safeError){const response=(error as{context?:Response}).context;if(response){try{const body=await response.clone().json() as{error?:string;message?:string};safeError=body.error??body.message}catch{safeError=undefined}}}if(error||safeError)setMessage(safeError??error?.message??"Invite failed");else{setMessage("Setup invitation sent and account linked.");setEmail("");setName("")}}
async function review(id:string,status:"approved"|"rejected"|"needs_information"){const notes=window.prompt("Staff notes (optional)")||null;const{error}=await getSupabaseBrowserClient()!.rpc("review_reseller_application",{p_request_id:id,p_status:status,p_staff_notes:notes});if(error)window.alert(error.message);else await load()}
if(access==="checking")return<main className="import-page">Checking staff access…</main>;if(access==="denied")return<main className="import-page"><section className="import-panel"><ShieldAlert/><h1>Staff access required</h1><Link href="/">Return to dashboard</Link></section></main>;
return<main className="import-page"><section className="import-shell"><span className="auth-eyebrow">Onward staff</span><h1>Administration</h1><p className="import-intro">Secure staff tools are separate from the customer dashboard.</p><Link className="primary-button" href="/admin/import"><FileSpreadsheet size={17}/>Open CSV Import Center</Link>
<h2 className="admin-section-title"><UserPlus size={23}/>Customer onboarding</h2><form className="onboarding-form" onSubmit={invite}><label>Approved email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="off"/></label><label>Customer name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Rewards account<select required value={accountId} onChange={e=>selectAccount(e.target.value)}><option value="">Select an account</option>{accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.display_name} · {a.current_tier}</option>)}</select></label><label>Relationship<select value={relationship} onChange={e=>setRelationship(e.target.value)} disabled={accounts.find(a=>a.id===accountId)?.kind!=="company"}><option value="individual">Individual</option><option value="company_member">Company member</option><option value="company_manager">Company manager</option></select></label><button className="primary-button" disabled={sending||!accountId}>{sending?"Sending…":"Send setup invitation"}</button>{message?<p className="onboarding-message" role="status">{message}</p>:null}</form>
<OperationsHealth/><RedemptionAdmin/><SupportAdmin/><h2 className="admin-section-title">Reseller applications</h2><div className="admin-request-list">{rows.length===0?<p>No applications submitted.</p>:rows.map(r=><article className="admin-request" key={r.id}><div><strong>{r.reward_accounts?.display_name??"Rewards account"}</strong><span>{r.status} · {r.completed_requirements}/3 requirements · {r.submitted_at?new Date(r.submitted_at).toLocaleDateString():"Not submitted"}</span></div><div className="admin-request-actions"><button onClick={()=>void review(r.id,"approved")}><CheckCircle2 size={15}/>Approve</button><button onClick={()=>void review(r.id,"needs_information")}><MessageSquareMore size={15}/>Request info</button><button onClick={()=>void review(r.id,"rejected")}><XCircle size={15}/>Reject</button></div></article>)}</div></section></main>}
